### PR TITLE
downgrade numpy to compatible version with tensorflow; downgrade hype…

### PR DESCRIPTION
**Pull request by sanfilip**
…ropt to compatible version with gradient-sdk

See: https://github.com/Paperspace/gradient-cli/issues/333#issuecomment-739605877

This passed the local test at the bottom of in the README.md, and also I tested as a local package install as follows

in the local repo dir ~/github/gradient-utils, in a virtualenv:
pip install dephell
dephell deps convert --from-format=poetry --from-path=pyproject.toml --to-format=setuppy --to-path=setup.py

in the testing venv:
pip install ~/github/gradient-utils
pip install gradient
pip install tensorflow
pip install gradient-sdk

no errors

### CODE REVIEW

**Review by weikaolun — DISMISSED** [review]

**Comment by lamroger** [comment]
Thanks @sanfilip! Ok if I take this over? 

https://github.com/Paperspace/gradient-utils/pull/35 adds a test and should pass with the change here.

**Comment by sanfilip** [comment]
Sure, transferring to you @lamroger

**Comment by sanfilip** [comment]
@lamroger also note I had to downgrade hyperopt too as gradient-sdk requires a hyperopt < 0.2.5.  probably should check for gradient-sdk install until we fully deprecate that/remove from our samples.  Also I'm not sure gradient-utils has been fully tested as a replacement for gradient-sdk in the scenarios where hyperopt was being used.  If hyperopt isn't actually being tested and used in gradient-utils, maybe we should remove it.

**Comment by lamroger** [comment]
@sanfilip That sounds good. I'll double check with @weikaolun about hyperopt and gradient-utils being a full replacement for gradient-sdk.

**Review by lamroger — APPROVED** [review]

**Pull request merged**
